name: Release Rules Checker
description: Determines release type based on the git ref and provided rules

inputs:
  release_tag_regex:
    required: false
    description: ''
    default: 'v[0-9]+(\.[0-9]+)'
  prerelease_tag_regex:
    required: false
    description: 'Regex to match '
    default: 'v[0-9]+(\.[0-9]+)(-([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?'
  prefix:
    required: false
    description: "(Optional) prefix of git tags to use. Example: 'sdk/'"
    default: ''
outputs:
  release-type:
    description: 'Type of the release. One of: [dev, pre-release, release]'
    value: ${{ steps.tag-check.outputs.release-type }}

runs:
  using: composite
  steps:
    - run: |
        release_type=dev
        release_regex='^${{ inputs.prefix }}${{ inputs.release_tag_regex }}$'
        prerelease_regex='^${{ inputs.prefix }}${{ inputs.prerelease_tag_regex }}$'
        if [[ '${{ github.event.ref }}' =~ ${release_regex} ]]; then
          release_type=release
        elif [[ '${{ github.event.ref }}' =~ ${prerelease_regex} ]]; then
          release_type=pre-release
        fi

        echo release_type=$release_type
        echo '::set-output name=release-type::$release_type'
      id: tag-check
      shell: bash