server:
  dev:
    enabled: true
  postStart:
    - /bin/sh
    - -c
    - |
      sleep 10 && \
      echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" && \
      echo "          $(date)             " && \
      echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
