server:
  dev:
    enabled: true
  postStart:
    - /bin/sh
    - -c
    - >
      sleep 30 && \
      echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$" && \
      echo "          $(date)             " && \
      echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
