{{- if eq .Values.enricher.enabled true -}}
{{- $resources := .Values.enricher.resources | default dict -}}
{{- $limits := $resources.limits | default dict -}}
{{- $requests := $resources.requests | default dict -}}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-enricher
  namespace: {{ .Release.Namespace }}
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-enricher-{{ .Release.Revision }}
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/minScale: "{{ .Values.enricher.minReplica }}"
        autoscaling.knative.dev/maxScale: "{{ .Values.enricher.maxReplica }}"
        autoscaling.knative.dev/target: "{{ .Values.enricher.targetConcurrency }}"
    spec:
      volumes:
{{ include "bq.volume" . | indent 6 }}
      containers:
      - image: "{{ .Values.enricher.image.registry }}{{ .Values.enricher.image.repository }}:{{ .Values.enricher.image.tag }}"
        ports:
        - containerPort: !!int {{ .Values.enricher.containerPort | default 8080 }}
        resources:
          limits:
            memory: {{ $limits.memory | default "512Mi" | quote }}
            cpu: {{ $limits.cpu | default "400m" | quote }}
          requests:
            memory: {{ $requests.memory | default "256Mi" | quote }}
            cpu: {{ $requests.cpu | default "200m" | quote }}
        volumeMounts:
{{ include "bq.volumeMount" . | indent 8 }}
        env:
{{ include "bq.env" . | indent 6 }}
{{- range $item := .Values.enricher.env }}
        - name: {{ $item.name }}
          value: {{ $item.value }}
{{- end }}
{{- end }}