logging:
  level: INFO
  resultlogger: Nop
monitoring:
  customMetrics:
    enabled: false
router:
  image:
    pullPolicy: IfNotPresent
    registry: #Docker registry
    repository: #Image repository
    tag: #Image tag
  livenessProbe:
    path: "/v1/internal/live"
  readinessProbe:
    path: "/v1/internal/ready"
  minReplica: 0
  maxReplica: 2
  targetConcurrency: 4
  resources:
    requests:
      memory: 250Mi
      cpu: 200m
    limits:
      memory: 250Mi
      cpu: 200m
  config:
    environment: #Environment name
    routes: #Array of routes info. Example shown below.
      # - id: route-a
      #   type: PROXY
      #   endpoint: route_url
      #   timeout: 50ms
    properties:
      default_route_id: #Default route name
      experiment_engine: nop
    timeout: 150ms
enricher:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    registry: #Docker registry
    repository: #Image repository
    tag: #Image tag
  minReplica: 0
  maxReplica: 2
  targetConcurrency: 1.1
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
  config:
    endpoint: #Relative endpoint. Eg: "echo?delay=10ms"
    timeout: 80ms
ensembler:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    registry: #Docker registry
    repository: #Image repository
    tag: #Image tag
  minReplica: 0
  maxReplica: 2
  targetConcurrency: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 250m
  config:
    endpoint: #Relative endpoint. Eg: "echo?delay=10ms"
    timeout: 80ms
fluentd:
  enabled: false