name: helm-chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
        with:
          version: 'v2.17.0'
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          charts_url: https://turing-ml.github.io/helm-charts
          charts_dir: charts
          owner: turing-ml
          repository: helm-charts
          helm_version: 2.17.0
          branch: gh-pages
          target_dir: charts/turing
          commit_username: romanwozniak
          commit_email: romeo.wozniak@gmail.com
