name: helm-chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          charts_url: https://turing-ml.github.io/helm-charts
          charts_dir: charts
          owner: turing-ml
          repository: helm-charts
