name: Test checks

on:
  push:
    paths:
      - ".github/workflows/infra.yaml"
      - ".github/workflows-resources/**"
    tags:
      - 'infra/v**'

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "OK"