name: Test checks

on:
  push:
    paths:
      - ".github/workflows/infra.yaml"
      - ".github/charts/**"
    branches:
      - '**'
    tags:
      - 'infra/v**'
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/infra.yaml"
      - ".github/charts/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - helm-version: 2.17.0
            chart-testing-version: 2.5.0
          - helm-version: 3.5.4
            chart-testing-version: 3.4.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v${{ matrix.helm-version }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
        with:
          version: v${{ matrix.chart-testing-version }}

      - name: Run chart-testing (lint)
        run: ct lint

  release:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Run chart-releaser
        run: |
          echo 'Release Charts!'