name: k3s

on: [push]

env:
  REGISTRY: ghcr.io
  TURING_VERSION: 0.0.0-build.1-164b88c
  MLP_VERSION: v1.4.14
  LOCAL_REGISTRY: registry.localhost:5000

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: turing-e2e
      ISTIO_VERSION: 1.9.9
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: "Setup local k8s cluster"
        id: single-cluster
        uses: AbsaOSS/k3d-action@v1.5.0
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          args: >-
            --agents 1
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - name: "Install Istio"
        working-directory: .github/workflows-resources
        run: |
          curl -v -L https://istio.io/downloadIstio | sh -
          export PATH=$PWD/istio-${{ env.ISTIO_VERSION }}/bin:$PATH

          ls -l ./

          istioctl install -f istio-minimal-operator.yaml

      - name: Log in to the GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}

      - run: |
          docker pull ${{ env.REGISTRY }}/gojek/mlp:${{ env.MLP_VERSION }}
          docker tag \
            ${{ env.REGISTRY }}/gojek/mlp:${{ env.MLP_VERSION }} \
            ${{ env.LOCAL_REGISTRY }}/gojek/mlp:${{ env.MLP_VERSION }}

          k3d image import ${{ env.LOCAL_REGISTRY }}/gojek/mlp:${{ env.MLP_VERSION }} \
            --cluster ${{ env.CLUSTER_NAME }} \
            --verbose

          docker image save \
            --output mlp-${{ env.MLP_VERSION }}.tar \
            ${{ env.LOCAL_REGISTRY }}/gojek/mlp:${{ env.MLP_VERSION }}

      - uses: actions/upload-artifact@v2
        with:
          name: mlp-${{ env.MLP_VERSION }}.tar
          path: mlp-${{ env.MLP_VERSION }}.tar

#      - uses: azure/setup-helm@v1
#        with:
#          version: 'v2.17.0'

      - uses: actions/checkout@v2
        with:
          repository: gojek/mlp
          ref: ${{ env.MLP_VERSION }}
          token: ${{ secrets.GH_PAT }}
          path: mlp

      - run: |
          helm install mlp ./mlp/charts/mlp \
            --dry-run \
            --set mlp.image.registry=${{ env.LOCAL_REGISTRY }} \
            --set mlp.image.repository=gojek/mlp \
            --set mlp.image.tag=${{ env.MLP_VERSION }} \
            --values mlp.helm-values.yaml

          helm install mlp ./mlp/charts/mlp \
            --set mlp.image.registry=${{ env.LOCAL_REGISTRY }} \
            --set mlp.image.repository=gojek/mlp \
            --set mlp.image.tag=${{ env.MLP_VERSION }} \
            --values mlp.helm-values.yaml

          kubectl apply -f ./github/workflows-resources/mlp.ingress.yaml

      - uses: jupyterhub/action-k8s-await-workloads@v1
        with:
          workloads: "deployment/mlp"
          max-restarts: 3

      - run: |
          kubectl get services
          kubectl get pods

      - run: |
          timeout --foreground 45 bash -c \
            "until curl -v -s --fail http://mlp.127.0.0.1.nip.io/v1/projects; do sleep 2; done"

  publish:
    runs-on: ubuntu-latest
    needs:
      - e2e
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: mlp-${{ env.MLP_VERSION }}.tar
          path: ./

      - run: |
          docker image load --input mlp-${{ env.MLP_VERSION }}.tar

          docker image ls



