name: openapi

on:
  push:
    branches:
      - main

jobs:
  swagger-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bundle openapi spec
        run: make bundle-openapi

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: static/swagger-ui
          spec-file: static/openapi.bundle.yaml

      - name: Upload openapi.json
        uses: actions/upload-artifact@v2
        with:
          name: swagger-ui
          path: static/swagger-ui/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: static/swagger-ui



