name: Publish

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      mlp_version:
        required: true
        type: string

jobs:
  publish:
    if: inputs.environment != ''
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: mlp-${{ inputs.mlp_version }}.tar
          path: ./

      - run: |
          docker image load --input mlp-${{ inputs.mlp_version }}.tar
          docker image ls