name: Reusable workflows

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  pull-image:
    runs-on: ubuntu-latest
    env:
      MLP_VERSION: 1.4.14
      REGISTRY: ghcr.io
    steps:
      - name: Log in to the GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker pull ${{ env.REGISTRY }}/gojek/mlp:v${{ env.MLP_VERSION }}

          docker image save \
            --output mlp-${{ env.MLP_VERSION }}.tar \
            ${{ env.REGISTRY }}/gojek/mlp:v${{ env.MLP_VERSION }}

      - uses: actions/upload-artifact@v2
        with:
          name: mlp-${{ env.MLP_VERSION }}.tar
          path: mlp-${{ env.MLP_VERSION }}.tar

  check-release-rules:
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.release-rules.outputs.release-type }}
    steps:
      - id: release-rules
        uses: ./.github/actions/release-rules

  publish:
    # Automatically publish release and pre-release artifacts.
    # As for dev releases, make it possible to publish artifacts
    # manually by approving 'deployment' in the 'manual' environment
    if: >-
      ( needs.check-release-rules.outputs.release-type != 'dev' )
        ||
      ( github.event_name != 'pull_request' )
    needs:
      - pull-image
      - check-release-rules
    uses: romanwozniak/workflows/.github/workflows/publish.yaml@main
    with:
      mlp_version: 1.4.14
      environment: ${{ needs.check-release-rules.outputs.release-type == 'dev' && 'e2e' || '' }}
